### ISSUE TITLE
Gyroflow-ofx with Gyroflow 1.0.0

### ISSUE THREAD

**Issue by Mcrubens** [ilya-epifanov/gyroflow-ofx#8]
Hi, 

In Gyroflow 1.0.0, how can I export the "Export (hopefully) stabilized keyframes for the whole clip" to get the .spl files? I only see the option to export the .gyroflow data. 

<img width="249" alt="Screenshot 2022-02-06 at 21 35 04" src="https://user-images.githubusercontent.com/78466877/152700327-a83f4f53-88ce-416f-9c5a-3832552a040d.png">

Thx for the help.

**Comment by ilya-epifanov** [comment]
You don't need that anymore. Please install a recent version and follow these instructions: https://github.com/ilya-epifanov/gyroflow-ofx#with-gyroflow-10
